
package atmmachine;

import sun.audio.*;
import java.io.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author maaz gheewale
 */
public class frmmain extends javax.swing.JFrame {

    Statement st;
    ResultSet rs;
    DBConnection db = new DBConnection();
    String n = "";
    String txtpin = "";
    String acc = "";
    int f = 0;
    String nnn = "";

    /** Creates new form frmmain */
    public frmmain(int x, String y) {
        f = x;
        nnn = y;
        initComponents();

        jifcardless.setVisible(false);
        jiftemppin.setVisible(false);
        jifmain.setVisible(false);
        jiforgpin.setVisible(false);
        jifchngpin.setVisible(false);
        jifcontinue.setVisible(false);
        jifbalinq.setVisible(false);
        jifwithdraw.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jifcardless = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmob = new javax.swing.JTextField();
        lblmob = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jiftemppin = new javax.swing.JInternalFrame();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttmppin = new javax.swing.JPasswordField();
        lblpin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jiforgpin = new javax.swing.JInternalFrame();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblorgpin = new javax.swing.JLabel();
        txtorgpin = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jifmain = new javax.swing.JInternalFrame();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jifcontinue = new javax.swing.JInternalFrame();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jLabel24 = new javax.swing.JLabel();
        lblcontinue = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jifchngpin = new javax.swing.JInternalFrame();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel21 = new javax.swing.JLabel();
        txtnewpin = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jifbalinq = new javax.swing.JInternalFrame();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        lblcontinue1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jifwithdraw = new javax.swing.JInternalFrame();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        lblcontinue2 = new javax.swing.JLabel();
        txtamt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        jifcardless.setBorder(null);
        jifcardless.setName("jifcardless"); // NOI18N
        jifcardless.setVisible(true);
        jifcardless.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jifcardlessInternalFrameOpened(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(frmmain.class);
        jLabel4.setIcon(resourceMap.getIcon("jLabel4.icon")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setForeground(resourceMap.getColor("jLabel5.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jLabel6.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        txtmob.setFont(resourceMap.getFont("txtmob.font")); // NOI18N
        txtmob.setText(resourceMap.getString("txtmob.text")); // NOI18N
        txtmob.setBorder(null);
        txtmob.setName("txtmob"); // NOI18N
        txtmob.setOpaque(false);
        txtmob.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtmobCaretUpdate(evt);
            }
        });
        txtmob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmobKeyPressed(evt);
            }
        });

        lblmob.setIcon(resourceMap.getIcon("lblmob.icon")); // NOI18N
        lblmob.setText(resourceMap.getString("lblmob.text")); // NOI18N
        lblmob.setName("lblmob"); // NOI18N
        lblmob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmobMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jifcardlessLayout = new javax.swing.GroupLayout(jifcardless.getContentPane());
        jifcardless.getContentPane().setLayout(jifcardlessLayout);
        jifcardlessLayout.setHorizontalGroup(
            jifcardlessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifcardlessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifcardlessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifcardlessLayout.createSequentialGroup()
                        .addGroup(jifcardlessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifcardlessLayout.createSequentialGroup()
                        .addComponent(lblmob)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifcardlessLayout.createSequentialGroup()
                        .addComponent(txtmob, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jifcardlessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jifcardlessLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jifcardlessLayout.setVerticalGroup(
            jifcardlessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifcardlessLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(108, 108, 108)
                .addComponent(txtmob, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(lblmob)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(jifcardlessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jifcardlessLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jifcardless.setBounds(0, -30, 870, 230);
        jLayeredPane1.add(jifcardless, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });
        jLabel2.setBounds(540, 360, 300, 80);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(resourceMap.getIcon("jLabel3.icon")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setBounds(0, 0, 870, 680);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jiftemppin.setBorder(null);
        jiftemppin.setName("jiftemppin"); // NOI18N
        jiftemppin.setVisible(true);
        jiftemppin.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jiftemppinInternalFrameOpened(evt);
            }
        });

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane2.setName("jLayeredPane2"); // NOI18N

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setForeground(resourceMap.getColor("jLabel9.foreground")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setBounds(60, 30, 770, 59);
        jLayeredPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel11.setForeground(resourceMap.getColor("jLabel11.foreground")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setBounds(380, 100, 140, 59);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txttmppin.setFont(resourceMap.getFont("txttmppin.font")); // NOI18N
        txttmppin.setText(resourceMap.getString("txttmppin.text")); // NOI18N
        txttmppin.setBorder(null);
        txttmppin.setEchoChar('X');
        txttmppin.setName("txttmppin"); // NOI18N
        txttmppin.setOpaque(false);
        txttmppin.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txttmppinCaretUpdate(evt);
            }
        });
        txttmppin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttmppinKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttmppinKeyTyped(evt);
            }
        });
        txttmppin.setBounds(0, 260, 860, 90);
        jLayeredPane2.add(txttmppin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblpin.setIcon(resourceMap.getIcon("lblpin.icon")); // NOI18N
        lblpin.setText(resourceMap.getString("lblpin.text")); // NOI18N
        lblpin.setName("lblpin"); // NOI18N
        lblpin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpinMouseClicked(evt);
            }
        });
        lblpin.setBounds(540, 480, 300, 80);
        jLayeredPane2.add(lblpin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setIcon(resourceMap.getIcon("jLabel8.icon")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setBounds(0, 0, 870, 760);
        jLayeredPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jiftemppinLayout = new javax.swing.GroupLayout(jiftemppin.getContentPane());
        jiftemppin.getContentPane().setLayout(jiftemppinLayout);
        jiftemppinLayout.setHorizontalGroup(
            jiftemppinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jiftemppinLayout.setVerticalGroup(
            jiftemppinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jiftemppin.setBounds(0, 690, 880, 60);
        jLayeredPane1.add(jiftemppin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jiforgpin.setName("jiforgpin"); // NOI18N
        jiforgpin.setVisible(true);
        jiforgpin.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jiforgpinInternalFrameOpened(evt);
            }
        });

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane3.setName("jLayeredPane3"); // NOI18N

        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setForeground(resourceMap.getColor("jLabel12.foreground")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jLabel12.setBounds(150, 30, 620, 70);
        jLayeredPane3.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel13.setForeground(resourceMap.getColor("jLabel13.foreground")); // NOI18N
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        jLabel13.setBounds(377, 120, 143, 50);
        jLayeredPane3.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblorgpin.setIcon(resourceMap.getIcon("lblorgpin.icon")); // NOI18N
        lblorgpin.setName("lblorgpin"); // NOI18N
        lblorgpin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblorgpinMouseClicked(evt);
            }
        });
        lblorgpin.setBounds(540, 480, 300, 80);
        jLayeredPane3.add(lblorgpin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtorgpin.setFont(resourceMap.getFont("txtorgpin.font")); // NOI18N
        txtorgpin.setBorder(null);
        txtorgpin.setEchoChar('X');
        txtorgpin.setName("txtorgpin"); // NOI18N
        txtorgpin.setOpaque(false);
        txtorgpin.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtorgpinCaretUpdate(evt);
            }
        });
        txtorgpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtorgpinKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtorgpinKeyTyped(evt);
            }
        });
        txtorgpin.setBounds(0, 230, 860, 90);
        jLayeredPane3.add(txtorgpin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setIcon(resourceMap.getIcon("jLabel10.icon")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setBounds(0, 0, 870, 760);
        jLayeredPane3.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jiforgpinLayout = new javax.swing.GroupLayout(jiforgpin.getContentPane());
        jiforgpin.getContentPane().setLayout(jiforgpinLayout);
        jiforgpinLayout.setHorizontalGroup(
            jiforgpinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        jiforgpinLayout.setVerticalGroup(
            jiforgpinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jiforgpin.setBounds(0, 750, 870, 60);
        jLayeredPane1.add(jiforgpin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jifmain.setName("jifmain"); // NOI18N
        jifmain.setVisible(true);
        jifmain.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jifmainInternalFrameOpened(evt);
            }
        });

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane4.setName("jLayeredPane4"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setForeground(resourceMap.getColor("jLabel7.foreground")); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setBounds(10, 30, 840, 80);
        jLayeredPane4.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setIcon(resourceMap.getIcon("jLabel16.icon")); // NOI18N
        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jLabel16.setBounds(550, 280, 300, 80);
        jLayeredPane4.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(resourceMap.getFont("jLabel18.font")); // NOI18N
        jLabel18.setForeground(resourceMap.getColor("jLabel18.foreground")); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel18.setName("jLabel18"); // NOI18N
        jLabel18.setBounds(0, 100, 850, 80);
        jLayeredPane4.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setIcon(resourceMap.getIcon("jLabel19.icon")); // NOI18N
        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jLabel19.setBounds(10, 290, 300, 80);
        jLayeredPane4.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setIcon(resourceMap.getIcon("jLabel20.icon")); // NOI18N
        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jLabel20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel20KeyPressed(evt);
            }
        });
        jLabel20.setBounds(20, 480, 300, 70);
        jLayeredPane4.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setIcon(resourceMap.getIcon("jLabel14.icon")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        jLabel14.setBounds(0, 0, 860, 740);
        jLayeredPane4.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jifmainLayout = new javax.swing.GroupLayout(jifmain.getContentPane());
        jifmain.getContentPane().setLayout(jifmainLayout);
        jifmainLayout.setHorizontalGroup(
            jifmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifmainLayout.createSequentialGroup()
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifmainLayout.setVerticalGroup(
            jifmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jifmain.setBounds(0, 810, 870, 70);
        jLayeredPane1.add(jifmain, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jifcontinue.setName("jifcontinue"); // NOI18N
        jifcontinue.setVisible(true);
        jifcontinue.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jifcontinueInternalFrameOpened(evt);
            }
        });

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane6.setName("jLayeredPane6"); // NOI18N

        jLabel24.setFont(resourceMap.getFont("jLabel24.font")); // NOI18N
        jLabel24.setForeground(resourceMap.getColor("jLabel24.foreground")); // NOI18N
        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        jLabel24.setBounds(30, 30, 830, 70);
        jLayeredPane6.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblcontinue.setIcon(resourceMap.getIcon("lblcontinue.icon")); // NOI18N
        lblcontinue.setName("lblcontinue"); // NOI18N
        lblcontinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcontinueMouseClicked(evt);
            }
        });
        lblcontinue.setBounds(540, 480, 300, 80);
        jLayeredPane6.add(lblcontinue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setName("jLabel27"); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jLabel27.setBounds(740, 620, 110, 120);
        jLayeredPane6.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setIcon(resourceMap.getIcon("jLabel26.icon")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        jLabel26.setBounds(0, 0, 880, 760);
        jLayeredPane6.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jifcontinueLayout = new javax.swing.GroupLayout(jifcontinue.getContentPane());
        jifcontinue.getContentPane().setLayout(jifcontinueLayout);
        jifcontinueLayout.setHorizontalGroup(
            jifcontinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jifcontinueLayout.setVerticalGroup(
            jifcontinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jifcontinue.setBounds(0, 940, 890, 70);
        jLayeredPane1.add(jifcontinue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jifchngpin.setName("jifchngpin"); // NOI18N
        jifchngpin.setVisible(true);
        jifchngpin.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jifchngpinInternalFrameOpened(evt);
            }
        });

        jLayeredPane5.setName("jLayeredPane5"); // NOI18N

        jLabel21.setFont(resourceMap.getFont("jLabel21.font")); // NOI18N
        jLabel21.setForeground(resourceMap.getColor("jLabel22.foreground")); // NOI18N
        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        jLabel21.setBounds(240, 70, 460, 59);
        jLayeredPane5.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtnewpin.setFont(resourceMap.getFont("txtnewpin.font")); // NOI18N
        txtnewpin.setBorder(null);
        txtnewpin.setEchoChar('X');
        txtnewpin.setName("txtnewpin"); // NOI18N
        txtnewpin.setOpaque(false);
        txtnewpin.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtnewpinCaretUpdate(evt);
            }
        });
        txtnewpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnewpinKeyPressed(evt);
            }
        });
        txtnewpin.setBounds(0, 280, 880, 90);
        jLayeredPane5.add(txtnewpin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setFont(resourceMap.getFont("jLabel22.font")); // NOI18N
        jLabel22.setForeground(resourceMap.getColor("jLabel22.foreground")); // NOI18N
        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        jLabel22.setBounds(280, 180, 370, 61);
        jLayeredPane5.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setIcon(resourceMap.getIcon("jLabel23.icon")); // NOI18N
        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jLabel23.setBounds(530, 480, 300, 80);
        jLayeredPane5.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setIcon(resourceMap.getIcon("jLabel15.icon")); // NOI18N
        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        jLabel15.setBounds(0, 0, 890, 760);
        jLayeredPane5.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jifchngpinLayout = new javax.swing.GroupLayout(jifchngpin.getContentPane());
        jifchngpin.getContentPane().setLayout(jifchngpinLayout);
        jifchngpinLayout.setHorizontalGroup(
            jifchngpinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        jifchngpinLayout.setVerticalGroup(
            jifchngpinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jifchngpin.setBounds(0, 880, 870, 60);
        jLayeredPane1.add(jifchngpin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jifbalinq.setName("jifbalinq"); // NOI18N
        jifbalinq.setVisible(true);

        jLayeredPane7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane7.setName("jLayeredPane7"); // NOI18N

        lblcontinue1.setIcon(resourceMap.getIcon("lblcontinue1.icon")); // NOI18N
        lblcontinue1.setName("lblcontinue1"); // NOI18N
        lblcontinue1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcontinue1MouseClicked(evt);
            }
        });
        lblcontinue1.setBounds(540, 480, 300, 80);
        jLayeredPane7.add(lblcontinue1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setFont(resourceMap.getFont("jLabel31.font")); // NOI18N
        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N
        jLabel31.setBounds(400, 50, 460, 70);
        jLayeredPane7.add(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel32.setFont(resourceMap.getFont("jLabel32.font")); // NOI18N
        jLabel32.setForeground(resourceMap.getColor("jLabel32.foreground")); // NOI18N
        jLabel32.setText(resourceMap.getString("jLabel32.text")); // NOI18N
        jLabel32.setName("jLabel32"); // NOI18N
        jLabel32.setBounds(190, 150, 579, 59);
        jLayeredPane7.add(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel33.setIcon(resourceMap.getIcon("jLabel33.icon")); // NOI18N
        jLabel33.setText(resourceMap.getString("jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N
        jLabel33.setBounds(200, 300, 80, 70);
        jLayeredPane7.add(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel34.setFont(resourceMap.getFont("jLabel34.font")); // NOI18N
        jLabel34.setText(resourceMap.getString("jLabel34.text")); // NOI18N
        jLabel34.setName("jLabel34"); // NOI18N
        jLabel34.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel34KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel34KeyTyped(evt);
            }
        });
        jLabel34.setBounds(290, 300, 460, 70);
        jLayeredPane7.add(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel30.setIcon(resourceMap.getIcon("jLabel30.icon")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N
        jLabel30.setBounds(0, 0, 890, 750);
        jLayeredPane7.add(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jifbalinqLayout = new javax.swing.GroupLayout(jifbalinq.getContentPane());
        jifbalinq.getContentPane().setLayout(jifbalinqLayout);
        jifbalinqLayout.setHorizontalGroup(
            jifbalinqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        jifbalinqLayout.setVerticalGroup(
            jifbalinqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jifbalinq.setBounds(0, 1010, 890, 550);
        jLayeredPane1.add(jifbalinq, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jifwithdraw.setName("jifwithdraw"); // NOI18N
        jifwithdraw.setVisible(true);
        jifwithdraw.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jifwithdrawInternalFrameOpened(evt);
            }
        });

        jLayeredPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane8.setName("jLayeredPane8"); // NOI18N

        lblcontinue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmmachine/resources/btncontinue.png"))); // NOI18N
        lblcontinue2.setName("lblcontinue2"); // NOI18N
        lblcontinue2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcontinue2MouseClicked(evt);
            }
        });
        lblcontinue2.setBounds(560, 490, 300, 80);
        jLayeredPane8.add(lblcontinue2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtamt.setBorder(null);
        txtamt.setName("txtamt"); // NOI18N
        txtamt.setOpaque(false);
        txtamt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtamtCaretUpdate(evt);
            }
        });
        txtamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtamtKeyPressed(evt);
            }
        });
        txtamt.setBounds(300, 320, 570, 90);
        jLayeredPane8.add(txtamt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmmachine/resources/IndianRupeesymbol.png"))); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        jLabel25.setBounds(200, 300, 123, 109);
        jLayeredPane8.add(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jifwithdrawLayout = new javax.swing.GroupLayout(jifwithdraw.getContentPane());
        jifwithdraw.getContentPane().setLayout(jifwithdrawLayout);
        jifwithdrawLayout.setHorizontalGroup(
            jifwithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        jifwithdrawLayout.setVerticalGroup(
            jifwithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jifwithdraw.setBounds(0, 1220, 890, 350);
        jLayeredPane1.add(jifwithdraw, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setBounds(250, 15, 860, 700);
        if (f == 1) {
            jifbalinq.setVisible(false);
            jifcardless.setVisible(false);
            jifchngpin.setVisible(false);
            jifmain.setVisible(false);
            jiforgpin.setVisible(false);
            jiftemppin.setVisible(false);
            jifcontinue.setBounds(0, -22, 860, 700);
            jLabel18.setText(nnn);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        jifcardless.setVisible(true);
        jifcardless.setBounds(0, -22, 860, 700);
        txtmob.requestFocus();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtmobCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtmobCaretUpdate
        // TODO add your handling code here:.
        if (txtmob.getText().trim().length() != 10) {
//        txtmob.getCaret().setVisible(false);
//        txtmob.getCaret().setVisible(false);
            txtmob.setHorizontalAlignment(SwingConstants.CENTER);
        }
}//GEN-LAST:event_txtmobCaretUpdate

    private void jifcardlessInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jifcardlessInternalFrameOpened
        // TODO add your handling code here:
        txtmob.getCaret().setVisible(false);

    }//GEN-LAST:event_jifcardlessInternalFrameOpened

    private void lblmobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmobMouseClicked

        try {
            // TODO add your handling code here:
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date date = new Date();

            n = txtmob.getText();
            st = db.DBC();
            Statement st1 = db.DBC();
            rs = st.executeQuery("Select regmob from tbltransfer where regmob='" + n + "'");
            if (rs.next()) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                jifcardless.setVisible(false);
                jiftemppin.setVisible(true);
                jiftemppin.setBounds(0, -22, 860, 700);

                ResultSet rs1 = st.executeQuery("Select accno,bcode from tbltransfer where regmob='" + n + "'");
                if (rs1.next()) {
                    int randomPIN = (int) (Math.random() * 9000) + 1000;
                    String a = rs1.getString("accno");
                    int q = st1.executeUpdate("update tbltransfer set tmppin=" + randomPIN + " where regmob='" + n + "'");
                    if (q > 0) {
                        System.out.print(randomPIN);
                        String strMsg = java.net.URLEncoder.encode("Your temporary otp is: " + randomPIN, "UTF-8");
                        callURL("http://api.smsala.com/api/SendSMS?api_id=API68232382092&api_password=HTbJxbbzEs&sms_type=T&encoding=T&sender_id=DROPIN&phonenumber=" + n + "&textmessage=" + strMsg);

                    }
                }

            } else {
               
                JOptionPane.showMessageDialog(rootPane, "Wrong Mobile Number", "Invalid", 1);
                //return;
                this.dispose();
                frmmain m = new frmmain(0, "");
                m.setVisible(true);
            }

        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(frmmain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmmain.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_lblmobMouseClicked

    private void jiftemppinInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jiftemppinInternalFrameOpened
        // TODO add your handling code here:
        lblpin.setBounds(546, 491, 300, 80);
    }//GEN-LAST:event_jiftemppinInternalFrameOpened

    private void txtmobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobKeyPressed
        //if((txtmob.getText().length()>0) && (txtmob.getText().length()<11)){
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_txtmobKeyPressed

    private void txttmppinCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txttmppinCaretUpdate
        // TODO add your handling code here:
        if (txttmppin.getText().trim().length() != 4) {
            //txttmppin.getCaret().setVisible(false);
            txttmppin.setHorizontalAlignment(SwingConstants.CENTER);
        }
    }//GEN-LAST:event_txttmppinCaretUpdate

    private void txttmppinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttmppinKeyPressed
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
    }//GEN-LAST:event_txttmppinKeyPressed

    private void lblpinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpinMouseClicked
        try {
            // TODO add your handling code here:
            txtpin = txttmppin.getText();
            st = db.DBC();
            String a = txtmob.getText();
            String b = txttmppin.getText();
            rs = st.executeQuery("select * from tbltransfer where regmob='" + n + "' and tmppin='" + txttmppin.getText() + "'");
            if (rs.next()) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                jiftemppin.setVisible(false);
                jiforgpin.setVisible(true);
                jiforgpin.setBounds(-8, -29, 860, 700);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid One Time Password", "Invalid Pin", 1);
                txttmppin.setText("");
                txttmppin.requestFocus();
                return;
            }

        } catch (SQLException ex) {
            Logger.getLogger(frmmain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblpinMouseClicked

    private void lblorgpinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblorgpinMouseClicked

        try {
           
            st = db.DBC();
            rs = st.executeQuery("Select replymob,bcode,accno,atmpin from tbltransfer where regmob=" + n + " and tmppin='" + txttmppin.getText() + "'");
            if (rs.next()) {
                String m = rs.getString("replymob");
                String bc = rs.getString("bcode");
                acc = rs.getString("accno");
                String pin = rs.getString("atmpin");

                if (pin.equals(txtorgpin.getText())) {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    jiforgpin.setVisible(false);
                    jifmain.setVisible(true);
                    jifmain.setBounds(-8, -29, 860, 700);
                    //st.executeUpdate("delete from tbltemppin where regmob='"+n+"'");                        
                    Statement st1 = db.DBC();
                    ResultSet rs2 = st1.executeQuery("select name from tbluserdetails where regmob='" + n + "'");
                    if (rs2.next()) {
                        jLabel18.setText(rs2.getString("name"));
                        System.out.print("............");
                       

                    }

                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(frmmain.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_lblorgpinMouseClicked

    private void txtorgpinCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtorgpinCaretUpdate
        // TODO add your handling code here:
        if (txtorgpin.getText().trim().length() != 4) {
            //txtorgpin.getCaret().setVisible(false);
            txtorgpin.setHorizontalAlignment(SwingConstants.CENTER);
        }
    }//GEN-LAST:event_txtorgpinCaretUpdate

    private void txtorgpinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtorgpinKeyPressed
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_txtorgpinKeyPressed

    private void jiforgpinInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jiforgpinInternalFrameOpened
        // TODO add your handling code here:
        lblorgpin.setBounds(546, 491, 300, 80);
    }//GEN-LAST:event_jiforgpinInternalFrameOpened

    private void jifmainInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jifmainInternalFrameOpened
    }//GEN-LAST:event_jifmainInternalFrameOpened

    private void txtnewpinCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtnewpinCaretUpdate

        if (txtnewpin.getText().trim().length() != 4) {
            txtnewpin.getCaret().setVisible(false);
            txtnewpin.setHorizontalAlignment(SwingConstants.CENTER);
        }
    }//GEN-LAST:event_txtnewpinCaretUpdate

    private void txtnewpinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewpinKeyPressed
        if ((txtnewpin.getText().length() <= 3)) {
            if (evt.getKeyCode() == 8) {
                txtnewpin.setEditable(true);
                return;
            }
            if ((evt.getKeyCode() < 96) || (evt.getKeyCode() > 105)) {
                //evt.setKeyCode(8);
                txtnewpin.setEditable(false);
            } else {

                txtnewpin.setEditable(true);
            }

        } else {
            if (evt.getKeyCode() == 8) {
                txtnewpin.setEditable(true);
                return;
            }
            txtnewpin.setEditable(false);

        }
    }//GEN-LAST:event_txtnewpinKeyPressed

    private void jifchngpinInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jifchngpinInternalFrameOpened
        jLabel23.setBounds(546, 491, 300, 80);
    }//GEN-LAST:event_jifchngpinInternalFrameOpened

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        try {
            // TODO add your handling code here:
            st = db.DBC();
            if (!txtnewpin.getText().equals("")) {
                int q = st.executeUpdate("update tbluserdetails set atmpin='" + txtnewpin.getText() + "' where accno='" + acc + "' ");
                if (q > 0) {
                    // System.out.print("donee.!");
                    jifchngpin.setVisible(false);
                    jifcontinue.setVisible(true);
                    jifcontinue.setBounds(-8, -29, 860, 700);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "New Password Cannot be Empty", "New Password", 1);
                txtnewpin.setText("");
                txtnewpin.requestFocus();
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmmain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void lblcontinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcontinueMouseClicked
        // TODO add your handling code here:
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        jifcontinue.setVisible(false);
        jifbalinq.setVisible(false);

        jifmain.setVisible(true);
        jifmain.setBounds(-8, -29, 860, 700);
    }//GEN-LAST:event_lblcontinueMouseClicked

    private void jifcontinueInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jifcontinueInternalFrameOpened
        // TODO add your handling code here:
        lblcontinue.setBounds(546, 891, 300, 80);
        if (f == 1) {
            frmreceipt r = new frmreceipt(acc);
            r.setVisible(true);
        }
    }//GEN-LAST:event_jifcontinueInternalFrameOpened

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        try {
            InputStream in;
            try {
                in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
                AudioStream audios = new AudioStream(in);
                AudioPlayer.player.start(audios);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            jifmain.setVisible(false);
            jifbalinq.setVisible(true);
            jifbalinq.setBounds(-8, -29, 860, 700);

            Statement st1 = db.DBC();
            Statement st = db.DBC();
            ResultSet rs2 = st1.executeQuery("select name from tbluserdetails where regmob='" + n + "'");
            if (rs2.next()) {
                jLabel31.setText(rs2.getString("name"));
            }
            ResultSet rs3 = st1.executeQuery("select bal from tbltransfer where regmob='" + n + "' ");
            if (rs3.next()) {
                jLabel34.setText(rs3.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmmain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void lblcontinue1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcontinue1MouseClicked
        // TODO add your handling code here:
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        jifcontinue.setVisible(false);
        //.setVisible(false);
        jifmain.setVisible(true);
        jifmain.setBounds(-8, -29, 860, 700);
    }//GEN-LAST:event_lblcontinue1MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
        this.setVisible(false);
        frmwitdraw m = new frmwitdraw(n, acc);
        m.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jifwithdrawInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jifwithdrawInternalFrameOpened
        
}//GEN-LAST:event_jifwithdrawInternalFrameOpened

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmend.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        this.dispose();
        frmmain m = new frmmain(0, "");
        m.setVisible(true);

    }//GEN-LAST:event_jLabel20MouseClicked

    private void lblcontinue2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcontinue2MouseClicked

    }//GEN-LAST:event_lblcontinue2MouseClicked

    private void txtamtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtamtCaretUpdate
        // TODO add your handling code here:
}//GEN-LAST:event_txtamtCaretUpdate

    private void txtamtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamtKeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_txtamtKeyPressed

    private void txttmppinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttmppinKeyTyped
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txttmppinKeyTyped

    private void txtorgpinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtorgpinKeyTyped
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorgpinKeyTyped

    private void jLabel34KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel34KeyPressed
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34KeyPressed

    private void jLabel34KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel34KeyTyped
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34KeyTyped

    private void jLabel20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel20KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmmain(0, "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JInternalFrame jifbalinq;
    private javax.swing.JInternalFrame jifcardless;
    private javax.swing.JInternalFrame jifchngpin;
    private javax.swing.JInternalFrame jifcontinue;
    private javax.swing.JInternalFrame jifmain;
    private javax.swing.JInternalFrame jiforgpin;
    private javax.swing.JInternalFrame jiftemppin;
    private javax.swing.JInternalFrame jifwithdraw;
    private javax.swing.JLabel lblcontinue;
    private javax.swing.JLabel lblcontinue1;
    private javax.swing.JLabel lblcontinue2;
    private javax.swing.JLabel lblmob;
    private javax.swing.JLabel lblorgpin;
    private javax.swing.JLabel lblpin;
    private javax.swing.JTextField txtamt;
    private javax.swing.JTextField txtmob;
    private javax.swing.JPasswordField txtnewpin;
    private javax.swing.JPasswordField txtorgpin;
    private javax.swing.JPasswordField txttmppin;
    // End of variables declaration//GEN-END:variables

    public void callURL(String strURL) {
        System.out.println(" URL is :" + strURL);
        try {
            java.net.URL obj = new java.net.URL(strURL);
            HttpURLConnection httpReq = (HttpURLConnection) obj.openConnection();
            httpReq.setDoOutput(true);
            httpReq.setInstanceFollowRedirects(true);
            httpReq.setRequestMethod("GET");
            String iStatus = httpReq.getResponseMessage();
            System.out.println("iStatus: " + iStatus);

        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
