
package atmmachine;

import sun.audio.*;
import java.io.*;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 ** @author maaz gheewale 
 */
public class frmwitdraw extends javax.swing.JFrame {

    Statement st;
    ResultSet rs;
    DBConnection db = new DBConnection();
    String n = "";
    //String txtpin="";
    String acc = "";

    /** Creates new form frmwitdraw */
    public frmwitdraw(String x, String y) {
        initComponents();
        n = x;
        acc = y;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblcontinue2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtamt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        lblcontinue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmmachine/resources/btncontinue.png"))); // NOI18N
        lblcontinue2.setName("lblcontinue2"); // NOI18N
        lblcontinue2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcontinue2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcontinue2MouseEntered(evt);
            }
        });
        jPanel1.add(lblcontinue2);
        lblcontinue2.setBounds(540, 540, 300, 80);

        jLabel37.setFont(new java.awt.Font("Vijaya", 1, 60));
        jLabel37.setName("jLabel37"); // NOI18N
        jPanel1.add(jLabel37);
        jLabel37.setBounds(360, 80, 310, 90);

        jLabel38.setFont(new java.awt.Font("Script MT Bold", 1, 48));
        jLabel38.setForeground(new java.awt.Color(255, 0, 51));
        jLabel38.setText("Please Enter Amount,");
        jLabel38.setName("jLabel38"); // NOI18N
        jPanel1.add(jLabel38);
        jLabel38.setBounds(200, 170, 470, 59);

        txtamt.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        txtamt.setBorder(null);
        txtamt.setName("txtamt"); // NOI18N
        txtamt.setOpaque(false);
        txtamt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtamtCaretUpdate(evt);
            }
        });
        txtamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtamtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtamtKeyTyped(evt);
            }
        });
        jPanel1.add(txtamt);
        txtamt.setBounds(300, 280, 490, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmmachine/resources/IndianRupeesymbol.png"))); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 280, 123, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmmachine/resources/Indian-Rupeenew.jpg"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            this.setBounds(250, 15, 860, 700);
            txtamt.requestFocus();
            st = db.DBC();
            ResultSet rs2 = st.executeQuery("select name from tbluserdetails where regmob='" + n + "'");
            if (rs2.next()) {
                //  jLabel37.setText(rs2.getString("name"));
                //  jLabel34.setText("bal" +".00");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmwitdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void lblcontinue2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcontinue2MouseClicked
        try {
            // TODO add your handling code here:
            st = db.DBC();
            float amt = 0;
            float t = 0;
            String bcode = "", mob = "", regmob = "";
            ResultSet rs4 = st.executeQuery("select bal,replymob,regmob from tbltransfer where accno='" + acc + "'");
            if (rs4.next()) {
                amt = rs4.getFloat(1);
                mob = rs4.getString(2);
                regmob = rs4.getString(3);
            }
            ResultSet rs1 = st.executeQuery("select bcode from tbluserdetails where accno='" + acc + "'");
            if (rs1.next()) {
                bcode = rs1.getString(1);
            }
            int sl = 1;
            rs = st.executeQuery("select * from tbltransaction");

            boolean f = rs.next();
            if (f == false) {
                sl = 1;
            } else {
                if (f == true) {
                    rs = st.executeQuery("select max(slno) from tbltransaction");
                }
                if (rs.next()) {
                    int i = rs.getInt(1);
                    i = i + 1;
                    sl = i;
                }
            }

            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date date = new Date();
            System.out.println(dateFormat.format(date));
            if (txtamt.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Amount Is Empty", "Error..!", 1);
                return;
            }
            float tamt = Float.parseFloat(txtamt.getText());
            float z = tamt % 100;
            int ff = 0, fff = 0;
            if (amt == tamt) {
                fff = 1;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error..! Insufficient Balance In Your Account", "Error..!", 1);
                return;
            }
            if (z == 0) {
                ff = 1;
            } else {
                JOptionPane.showMessageDialog(rootPane, "The Amount Should Be In Multiple Of 100", "Check The Amount", 1);
                return;
            }
            if (ff == 1 && fff == 1) {
//                rs = st.executeQuery("select max(slno) from tbltransaction where accno='" + acc + "'");
//                if (rs.next()) {
//                    rs = st.executeQuery("select bal from tbltransaction where slno=" + rs.getInt(1) + "");
//                    rs.next();
//                    t = rs.getInt(1) - tamt;
//                }
//                String msg = "ATM Transfer: " + regmob;
//                int q = st.executeUpdate("insert into tbltransaction values(" + sl + ",'" + bcode + "','" + acc + "','" + dateFormat.format(date) + "','" + msg + "','0'," + txtamt.getText() + "," + t + ")");
//                if (q > 0) {
                st.executeUpdate("delete from tbltransfer where accno='" + acc + "' and replymob='" + mob + "'");
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmrecipt.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Transaction Is Sucessfully Done. Take Your Cash", "Transaction", 1);
                this.dispose();
                int flag = 1;
                frmmain m = new frmmain(flag, "");
                m.setVisible(true);
                frmreceipt a = new frmreceipt(acc);
                a.setVisible(true);
                this.dispose();
            }

        } catch (SQLException ex) {
            Logger.getLogger(frmwitdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_lblcontinue2MouseClicked

    private void txtamtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtamtCaretUpdate
        // TODO add your handling code here:
}//GEN-LAST:event_txtamtCaretUpdate

    private void txtamtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamtKeyPressed
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_txtamtKeyPressed

    private void lblcontinue2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcontinue2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcontinue2MouseEntered

    private void txtamtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamtKeyTyped
        InputStream in;
        try {
            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE4\\src\\atmmachine\\atmselect.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamtKeyTyped

    public void callURL(String strURL) {
        System.out.println(" URL is :" + strURL);
        try {
            java.net.URL obj = new java.net.URL(strURL);
            HttpURLConnection httpReq = (HttpURLConnection) obj.openConnection();
            httpReq.setDoOutput(true);
            httpReq.setInstanceFollowRedirects(true);
            httpReq.setRequestMethod("GET");
            String iStatus = httpReq.getResponseMessage();
            System.out.println("iStatus: " + iStatus);

        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmwitdraw("", "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcontinue2;
    private javax.swing.JTextField txtamt;
    // End of variables declaration//GEN-END:variables
}