/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BANKLOGIN.java
 *
 * 
 */
package imfromatm;

import sun.audio.*;
import java.io.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author maaz gheewale
 */
public class BANKLOGIN extends javax.swing.JFrame {

    DBConnection db = new DBConnection();
    Statement st;
    ResultSet rs;
    String bank;

    /** Creates new form BANKLOGIN */
    public BANKLOGIN() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtbankpass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbbank = new javax.swing.JComboBox();
        cmbifsc = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setName("jPanel2"); // NOI18N

        txtbankpass.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtbankpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbankpass.setName("txtbankpass"); // NOI18N
        txtbankpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbankpassKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel10.setText("Bank Name");
        jLabel10.setName("jLabel10"); // NOI18N

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Login");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jButton4.setText("Cancel");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Bank Login");
        jLabel1.setName("jLabel1"); // NOI18N

        cmbbank.setFont(new java.awt.Font("Times New Roman", 0, 14));
        cmbbank.setName("cmbbank"); // NOI18N
        cmbbank.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbankItemStateChanged(evt);
            }
        });
        cmbbank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbbankKeyPressed(evt);
            }
        });

        cmbifsc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbifsc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "." }));
        cmbifsc.setName("cmbifsc"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel11.setText("Bank Code");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel12.setText("Password");
        jLabel12.setName("jLabel12"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbankpass, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(cmbifsc, 0, 182, Short.MAX_VALUE)
                            .addComponent(cmbbank, 0, 182, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbbank, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbifsc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbankpass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbankpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbankpassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            jButton3ActionPerformed(null);
        }
}//GEN-LAST:event_txtbankpassKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String a = "", b = "", m = "", n = "", c = "", o = "";

            if (cmbifsc.getSelectedItem().equals(".")) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Select Bank/Bank Code");
                return;
            }
            a = cmbbank.getSelectedItem().toString();
            b = cmbifsc.getSelectedItem().toString();
            c = txtbankpass.getText();

            if (a.equals("Select Bank")) {
                JOptionPane.showMessageDialog(rootPane, "Please Select Bank", "Login", 1);
                cmbbank.requestFocus(true);
                return;
            } else if (b.equals("Select Bank Code")) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Select Bank code", "Login", 1);
                cmbifsc.requestFocus(true);
                return;
            } else if (c.equals("")) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Password", "Login", 1);
                txtbankpass.requestFocus(true);
                return;
            }

            st = db.DBC();
            rs = st.executeQuery("select * from tblbank where bankname='" + a + "' and bpass='" + c + "'");
            if (rs.next()) {
                m = rs.getString("bankname");
                n = rs.getString("bpass");
                o = rs.getString("bcode");
            }
            if (a.equals(m) && b.equals(o) && c.equals(n)) {
                // JOptionPane.showMessageDialog(rootPane, "Login Sucessfull","Login", 1);
                main1 af = new main1(a, b);
                af.setVisible(true);
                dispose();
                return;
            } else {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid Bank Name/Bank Code/Password", "Login", 0);
//                txtuser.setText("");
//                txtpwd.setText("");
//                txtuser.requestFocus(true);
                return;
            }
        } catch (SQLException ex) {
            //Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        FirstLogin f = new FirstLogin();
        f.setVisible(true);
//        this.dispose();
}//GEN-LAST:event_jButton4ActionPerformed

    private void cmbbankItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbankItemStateChanged
        try {
            st = db.DBC();
            bank = cmbbank.getSelectedItem().toString();
            System.out.print(bank);
            ResultSet r = st.executeQuery("Select bcode from tblbank where bankname='" + bank + "'");
            boolean b = r.next();
            System.out.print(b);
            if (b == true) {
                cmbifsc.removeAllItems();
                cmbifsc.addItem("Select Bank Code");

                ResultSet rs1 = st.executeQuery("Select bcode from tblbank where bankname='" + bank + "'");
                while (rs1.next()) {
                    cmbifsc.addItem(rs1.getString(1));
                }

                cmbifsc.requestFocus();
            } else {
                System.out.print("ouuuttt");
            }

        } catch (SQLException ex) {
            //Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbbankItemStateChanged

    private void cmbbankKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbbankKeyPressed
}//GEN-LAST:event_cmbbankKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            this.setBounds(480, 100, 475, 300);
            st = db.DBC();
            rs = st.executeQuery("Select distinct(bankname) from tblbank");
            cmbbank.addItem("Select Bank");
            while (rs.next()) {
                cmbbank.addItem(rs.getString(1));
            }
        } catch (Exception ex) {
            System.out.print(ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BANKLOGIN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbbank;
    private javax.swing.JComboBox cmbifsc;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtbankpass;
    // End of variables declaration//GEN-END:variables
}
