/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * transaction.java
 *
 * 
 */
package imfromatm;

import sun.audio.*;
import java.io.*;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 ** @author maaz gheewale 
 */
public class transaction extends javax.swing.JFrame {

    String action = "";
    Statement st;
    ResultSet rs;
    DBConnection db = new DBConnection();
    int sl;
    String bcode;

    /** Creates new form transaction */
    public transaction(String bc) {
        bcode = bc;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtaddr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtatmcard = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtmob = new javax.swing.JTextField();
        txtacc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtbal = new javax.swing.JTextField();
        btnclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel8.setText("Full Name                  ");
        jLabel8.setName("jLabel8"); // NOI18N

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtname.setName("txtname"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel9.setText("Address                      ");
        jLabel9.setName("jLabel9"); // NOI18N

        txtaddr.setEditable(false);
        txtaddr.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtaddr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtaddr.setName("txtaddr"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel10.setText("E-Mail                         ");
        jLabel10.setName("jLabel10"); // NOI18N

        txtatmcard.setEditable(false);
        txtatmcard.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtatmcard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtatmcard.setName("txtatmcard"); // NOI18N

        txtmail.setEditable(false);
        txtmail.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmail.setName("txtmail"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel14.setText("ATM Card No             ");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel11.setText("Mobile No              ");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel13.setText("Account No             ");
        jLabel13.setName("jLabel13"); // NOI18N

        txtmob.setEditable(false);
        txtmob.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtmob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmob.setName("txtmob"); // NOI18N

        txtacc.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtacc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtacc.setName("txtacc"); // NOI18N
        txtacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaccKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel18.setText("Balance                     ");
        jLabel18.setName("jLabel18"); // NOI18N

        txtamount.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtamount.setName("txtamount"); // NOI18N
        txtamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtamountKeyPressed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnreset.setText("Save");
        btnreset.setName("btnreset"); // NOI18N
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel17.setText("Credit Amount           ");
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Transaction Master");
        jLabel1.setName("jLabel1"); // NOI18N

        txtbal.setEditable(false);
        txtbal.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtbal.setText("0.00");
        txtbal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbal.setName("txtbal"); // NOI18N

        btnclose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnclose.setText("Cancel");
        btnclose.setName("btnclose"); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addGap(24, 24, 24)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtacc, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txtatmcard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txtaddr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txtmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txtmob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbal, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txtamount, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))))
                        .addGap(117, 117, 117))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnclose)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(144, 144, 144))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtacc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtatmcard, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmob, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclose)
                    .addComponent(btnreset))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        try {

            int s1 = 0;
            String s = txtamount.getText();
            for (int i = 0; i < s.length(); i++) {
                if (!Character.isDigit(s.charAt(i))) {
                    s1++;
                }
            }
            if (s1 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Amount.", "Amount", 1);
                txtamount.requestFocus();
                return;
            }

            if (txtname.getText().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please check Account No.", "Amount", 1);
                txtamount.requestFocus();
                return;
            }
            if ((txtamount.getText()).equals("")) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Amount ", "Amount", 1);
                txtamount.requestFocus();
                return;
            }


            st = db.DBC();
            float abc = 0;
            float cr = 0;
            rs = st.executeQuery("select * from tbltransaction");

            boolean f = rs.next();
            if (f == false) {
                sl = 1;
            } else {
                if (f == true) {
                    rs = st.executeQuery("select max(slno) from tbltransaction");
                }
                if (rs.next()) {
                    int i = rs.getInt(1);
                    i = i + 1;
                    sl = i;
                }

            }
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date date = new Date();
            System.out.println(dateFormat.format(date));
            //System.out.print(sl,);
            float d = 0;

            ResultSet rs1 = st.executeQuery("Select MAX(slno) from tbltransaction where accno='" + txtacc.getText() + "' ");
            if (rs1.next()) {
                ResultSet rs2 = st.executeQuery("select bal from tbltransaction where slno=" + rs1.getString(1) + "");
                if (rs2.next()) {
                    txtbal.setText(rs2.getString("bal"));
                    abc = Float.parseFloat(txtbal.getText());
                }

            }
            float bal = abc + (Float.parseFloat(txtamount.getText()));
            int q = st.executeUpdate("insert into tbltransaction values(" + sl + ",'" + bcode + "','" + txtacc.getText() + "','" + dateFormat.format(date) + "','Cash Deposit'," + txtamount.getText() + "," + d + "," + bal + ")");
            if (q > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\complete.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Transaction Is Sucessfully Done.", "Transaction", 1);
                String strMsg = java.net.URLEncoder.encode("Amt of Rs." + txtamount.getText() + " is added to your Acc no " + txtacc.getText(), "UTF-8");
                callURL("http://api.smsala.com/api/SendSMS?api_id=API68232382092&api_password=HTbJxbbzEs&sms_type=T&encoding=T&sender_id=DROPIN&phonenumber=" + txtmob.getText() + "&textmessage=" + strMsg);
                clearform();
            } else {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Error in Transaction", "Transaction", 1);
            }
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnresetActionPerformed

    public void callURL(String strURL) {
        System.out.println(" URL is :" + strURL);
        try {
            java.net.URL obj = new java.net.URL(strURL);
            HttpURLConnection httpReq = (HttpURLConnection) obj.openConnection();
            httpReq.setDoOutput(true);
            httpReq.setInstanceFollowRedirects(true);
            httpReq.setRequestMethod("GET");
            String iStatus = httpReq.getResponseMessage();
            System.out.println("iStatus: " + iStatus);

        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void txtaccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccKeyPressed
        if (evt.getKeyCode() == 10) {
            try {
                if ((txtacc.getText()).equals("")) {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Please Enter Account Number", "Account Number", 1);
                    txtacc.requestFocus();
                    return;
                }
                int s2 = 0;
                String s3 = txtacc.getText();
                for (int i = 0; i < s3.length(); i++) {
                    if (!Character.isDigit(s3.charAt(i))) {
                        s2++;
                    }
                }
                if (s2 > 0) {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Please Enter valid Account No.", "Account Number", 1);
                    txtacc.requestFocus();
                    return;
                } else {
                    st = db.DBC();
                    rs = st.executeQuery("Select * from tbluserdetails where accno='" + txtacc.getText() + "'");
                    if (rs.next()) {
                        txtacc.setText(rs.getString("accno"));
                        txtname.setText(rs.getString("name"));
                        txtaddr.setText(rs.getString("address"));
                        txtmail.setText(rs.getString("email"));
                        txtmob.setText(rs.getString("regmob"));
                        txtatmcard.setText(rs.getString("atmcard"));
                        txtamount.requestFocus();

                        ResultSet rs1 = st.executeQuery("Select MAX(slno) from tbltransaction where accno='" + txtacc.getText() + "' ");
                        if (rs1.next()) {
                            ResultSet rs2 = st.executeQuery("select bal from tbltransaction where slno=" + rs1.getString(1) + "");
                            if (rs2.next()) {
                                txtbal.setText(rs2.getString("bal"));
                            } else {
                                InputStream in;
                                try {
                                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                                    AudioStream audios = new AudioStream(in);
                                    AudioPlayer.player.start(audios);
                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(null, e);
                                }
                                JOptionPane.showMessageDialog(rootPane, "Current Balance is 0 Rs ", "Current balance", 1);
                            }
                        }
                    } else {
                        InputStream in;
                        try {
                            in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                            AudioStream audios = new AudioStream(in);
                            AudioPlayer.player.start(audios);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                        JOptionPane.showMessageDialog(rootPane, " Invalid Account Number", "Account Number", 1);
                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtaccKeyPressed

    private void txtamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamountKeyPressed
        if (evt.getKeyCode() == 10) {
            btnresetActionPerformed(null);
        }
    }//GEN-LAST:event_txtamountKeyPressed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new transaction("").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtacc;
    private javax.swing.JTextField txtaddr;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtatmcard;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

    public void clearform() {
        txtacc.setText("");
        txtaddr.setText("");
        txtamount.setText("");
        txtatmcard.setText("");
        txtbal.setText("");
        txtmail.setText("");
        txtmob.setText("");
        txtname.setText("");
        txtacc.requestFocus();
    }
}
