/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserDetails.java
 *
 *  
 */
package imfromatm;
import sun.audio.*;
import java.io.*;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 ** @author maaz gheewale 
 */
public class UserDetails extends javax.swing.JFrame {

    Statement st;
    ResultSet rs, ss;
    DBConnection db = new DBConnection();
    String accno,oldmail;
    String lgn, bcode;
    static Pattern pattern = null;
    static Matcher matcher = null;

    /** Creates new form UserDetails */
    public UserDetails(String x, String bc) {
        lgn = x;
        bcode = bc;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtacc = new javax.swing.JTextField();
        txtmob = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtatmcard = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        txtatmpin = new javax.swing.JPasswordField();
        cmbacctype = new javax.swing.JComboBox();
        txtifsc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddr = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        txtpan = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtaccesspin = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        txtbname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Customer Details");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel10.setText("E-Mail");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel11.setText("Mobile No");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel12.setText("Type Of Account");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel13.setText("Account No");
        jLabel13.setName("jLabel13"); // NOI18N

        txtacc.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtacc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtacc.setName("txtacc"); // NOI18N
        txtacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaccKeyPressed(evt);
            }
        });

        txtmob.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtmob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmob.setName("txtmob"); // NOI18N
        txtmob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmobKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel9.setText("Address");
        jLabel9.setName("jLabel9"); // NOI18N

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtname.setName("txtname"); // NOI18N
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel8.setText("Full Name");
        jLabel8.setName("jLabel8"); // NOI18N

        txtmail.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmail.setName("txtmail"); // NOI18N
        txtmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmailKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel14.setText("ATM Card No");
        jLabel14.setName("jLabel14"); // NOI18N

        txtatmcard.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtatmcard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtatmcard.setName("txtatmcard"); // NOI18N
        txtatmcard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtatmcardKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel15.setText("ATM Card PIN");
        jLabel15.setName("jLabel15"); // NOI18N

        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btnsave.setText("Save");
        btnsave.setName("btnsave"); // NOI18N
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btnsearch.setText("Search");
        btnsearch.setName("btnsearch"); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btnedit.setText("Edit");
        btnedit.setEnabled(false);
        btnedit.setName("btnedit"); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btndelete.setText("Delete");
        btndelete.setEnabled(false);
        btndelete.setName("btndelete"); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btnreset.setText("Reset");
        btnreset.setName("btnreset"); // NOI18N
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        txtatmpin.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtatmpin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtatmpin.setName("txtatmpin"); // NOI18N
        txtatmpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtatmpinKeyPressed(evt);
            }
        });

        cmbacctype.setFont(new java.awt.Font("Times New Roman", 0, 14));
        cmbacctype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "CURRENT ACCOUNT", "SAVING ACCOUNT" }));
        cmbacctype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbacctype.setName("cmbacctype"); // NOI18N
        cmbacctype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbacctypeKeyPressed(evt);
            }
        });

        txtifsc.setEditable(false);
        txtifsc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtifsc.setName("txtifsc"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel16.setText("Bank Name");
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel17.setText("Branch Code");
        jLabel17.setName("jLabel17"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtaddr.setColumns(20);
        txtaddr.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtaddr.setRows(5);
        txtaddr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtaddr.setName("txtaddr"); // NOI18N
        jScrollPane1.setViewportView(txtaddr);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setText("ADHAR No.");
        jLabel18.setName("jLabel18"); // NOI18N

        txtpan.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpan.setName("txtpan"); // NOI18N
        txtpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpanKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel19.setText("Bank Access Pin");
        jLabel19.setName("jLabel19"); // NOI18N

        txtaccesspin.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtaccesspin.setText("0000");
        txtaccesspin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtaccesspin.setName("txtaccesspin"); // NOI18N
        txtaccesspin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccesspinActionPerformed(evt);
            }
        });
        txtaccesspin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaccesspinKeyPressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel21.setText(":");
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel22.setText(":");
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel23.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel23.setText(":");
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel24.setText(":");
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel25.setText(":");
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel26.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel26.setText(":");
        jLabel26.setName("jLabel26"); // NOI18N

        jLabel27.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel27.setText(":");
        jLabel27.setName("jLabel27"); // NOI18N

        jLabel28.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel28.setText(":");
        jLabel28.setName("jLabel28"); // NOI18N

        jLabel29.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel29.setText(":");
        jLabel29.setName("jLabel29"); // NOI18N

        jLabel30.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel30.setText(":");
        jLabel30.setName("jLabel30"); // NOI18N

        jLabel31.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel31.setText(":");
        jLabel31.setName("jLabel31"); // NOI18N

        jLabel32.setFont(new java.awt.Font("Dialog 12 12", 1, 13));
        jLabel32.setText(":");
        jLabel32.setName("jLabel32"); // NOI18N

        btnclose.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btnclose.setText("Cancel");
        btnclose.setName("btnclose"); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        txtbname.setEditable(false);
        txtbname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtbname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbname.setName("txtbname"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtacc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                    .addComponent(txtatmcard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                    .addComponent(txtatmpin, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                    .addComponent(txtaccesspin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)))
                            .addComponent(txtpan, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtbname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(cmbacctype, javax.swing.GroupLayout.Alignment.LEADING, 0, 381, Short.MAX_VALUE)
                            .addComponent(txtmob, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(txtmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(txtifsc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                        .addGap(292, 292, 292))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel3)
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel21))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel22)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtmob, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbacctype, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(jLabel25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel26)
                    .addComponent(txtbname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtifsc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtacc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtatmcard, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtatmpin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaccesspin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel19)))
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnsearch)
                    .addComponent(btnedit)
                    .addComponent(btndelete)
                    .addComponent(btnreset)
                    .addComponent(btnclose))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
            // TODO add your handling code here:
            if (txtname.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Full Name. ", "User Name", 1);
                txtname.requestFocus();
                return;
            } else if (txtaddr.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Address", "Address", 1);
                txtaddr.requestFocus();
                return;
            } else if (txtmail.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Email-ID", "Email", 1);
                txtmail.requestFocus();
                return;
            } else if (txtmob.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Mobile No", "Contact", 1);
                txtmob.requestFocus();
                return;
            } else if (cmbacctype.getSelectedItem().equals("Select")) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Select Account Type", "Branch", 1);
                cmbacctype.requestFocus();
                return;
            } else if (txtpan.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Adhar Card No.", "PAN", 1);
                txtpan.requestFocus();
                return;
            } else if (txtacc.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Account No", "Account", 1);
                txtacc.requestFocus();
                return;
            } else if (txtatmcard.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter ATM Card No.", "ATM Card", 1);
                txtatmcard.requestFocus();
                return;

            } else if (txtatmpin.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Please Enter ATM Access Pin", "Access Pin", 1);
                txtatmpin.requestFocus();
                return;
            } else if (txtaccesspin.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Bank Access Pin", "Bank Pin", 1);
                txtaccesspin.requestFocus();
                return;
            } else if (txtmob.getText().length() != 10) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Mobile No", "Contact", 1);
                txtmob.requestFocus();
                return;
            } else if (txtpan.getText().length() != 12) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Adhar Card No", "PAN No", 1);
                txtpan.requestFocus();
                return;
            } else if (txtatmcard.getText().length() != 16) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid ATM Card No", "ATM Card", 1);
                txtatmcard.requestFocus();
                return;
            } else if (txtacc.getText().length() != 16) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Account No", "Address", 1);
                txtacc.requestFocus();
                return;
            } else if (txtatmpin.getText().length() != 4) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid ATM Pin", "ATM Pin", 1);
                txtatmpin.requestFocus();
                return;
            } else if (txtaccesspin.getText().length() != 4) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Bank Access Pin", "Bank Pin", 1);
                txtaccesspin.requestFocus();
                return;
            }
            int s1 = 0;
            String s = txtmob.getText();
            for (int i = 0; i < s.length(); i++) {
                if (!Character.isDigit(s.charAt(i))) {
                    s1++;
                }
            }
            if (s1 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid Mobile No.", "Contact", 1);
                txtmob.requestFocus();
                return;
            }

            int s2 = 0;
            String s3 = txtacc.getText();
            for (int i = 0; i < s3.length(); i++) {
                if (!Character.isDigit(s3.charAt(i))) {
                    s2++;
                }
            }
            if (s2 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid Account No.", "Account", 1);
                txtacc.requestFocus();
                return;
            }
            int s4 = 0;
            String s5 = txtatmcard.getText();
            for (int i = 0; i < s5.length(); i++) {
                if (!Character.isDigit(s5.charAt(i))) {
                    s4++;
                }
            }
            if (s4 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid ATM Card No.", "aTM Card", 1);
                txtatmcard.requestFocus();
                return;
            }
            int s6 = 0;
            String s7 = txtatmpin.getText();
            for (int i = 0; i < s7.length(); i++) {
                if (!Character.isDigit(s7.charAt(i))) {
                    s6++;
                }
            }
            if (s6 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid ATM Pin.", "ATM Pin", 1);
                txtatmpin.requestFocus();
                return;
            }
            int s8 = 0;
            String s9 = txtaccesspin.getText();
            for (int i = 0; i < s9.length(); i++) {
                if (!Character.isDigit(s9.charAt(i))) {
                    s8++;
                }
            }
            if (s8 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid Bank Access Pin.", "Bank Pin", 1);
                txtaccesspin.requestFocus();
                return;
            }

            String name = txtname.getText();
            String patternvalidation = "[a-zA-Z \\s]+\\.?";
            pattern = Pattern.compile(patternvalidation);
            matcher = pattern.matcher(name);
            if (!matcher.matches()) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Name", "Name", 1);
                txtname.requestFocus();
                return;
            }

            String email = txtmail.getText();
            String patternvalidation1 = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
            pattern = Pattern.compile(patternvalidation1);
            matcher = pattern.matcher(email);
            if (!matcher.matches()) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Email-Id", "Email", 1);
                txtname.requestFocus();
                return;
            }

            st = db.DBC();
            rs = st.executeQuery("select * from tbluserdetails where  accno='" + txtacc.getText() + "'");

            if (rs.next()) {//here
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Customer already present with Account No: " + txtacc.getText() + " and Name: " + rs.getString(3), "Save", 0);
                txtname.requestFocus();
                return;
            } else {
                int q = st.executeUpdate("insert into tbluserdetails values('" + cmbacctype.getSelectedItem() + "','" + txtacc.getText() + "','" + txtname.getText() + "','" + txtaddr.getText() + "','" + txtmail.getText() + "','" + txtmob.getText() + "','" + txtatmpin.getText() + "','" + txtatmcard.getText() + "','" + txtbname.getText() + "','" + txtifsc.getText() + "','" + txtpan.getText() + "','" + txtaccesspin.getText() + "')");
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\complete.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Customer Added successfully", "Save", 1);
                clearform();
                txtname.requestFocus();
                return;

            }
        } catch (SQLException ex) {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_btnsaveActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        st = db.DBC();
        int i = 0;
        String r = JOptionPane.showInputDialog("Enter Account No", "Account No");
        if ((r.equals("Account No") && r.equals(""))) {
            return;
        } else {
            try {
                rs = st.executeQuery("Select * from tbluserdetails where accno='" + r + "'");
                while (rs.next()) {
                    i++;
                    cmbacctype.setSelectedItem(rs.getString("acctype"));
                    txtacc.setText(rs.getString("accno"));
                    txtname.setText(rs.getString("name"));
                    txtaddr.setText(rs.getString("address"));
                    txtmail.setText(rs.getString("email"));
                    txtmob.setText(rs.getString("regmob"));
                    txtatmpin.setText(rs.getString("atmpin"));
                    txtaccesspin.setText(rs.getString("accesspin"));
                    txtatmcard.setText(rs.getString("atmcard"));
                    txtbname.setText(rs.getString("bankname"));
                    txtifsc.setText(rs.getString("bcode"));
                    txtpan.setText(rs.getString("pan"));
                    accno = txtacc.getText();
                    oldmail = txtmail.getText();
                }
                if (i > 0) {
                    btnsave.setEnabled(false);
                    btnsearch.setEnabled(true);
                    btnedit.setEnabled(true);
                    btndelete.setEnabled(true);

                    txtpan.setEditable(false);
                    txtacc.setEditable(false);
                    txtatmcard.setEditable(false);
                    txtatmpin.setEditable(false);
                    txtaccesspin.setEditable(false);

                } else {
                    InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                    JOptionPane.showMessageDialog(rootPane, "Invalid Account No.", "Search", 1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(BankMaster.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_btnsearchActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        try {

            if (txtname.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Full Name. ", "User Name", 1);
                txtname.requestFocus();
                return;
            } else if (txtaddr.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Address", "Address", 1);
                txtaddr.requestFocus();
                return;
            } else if (txtmail.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Email-ID", "Email", 1);
                txtmail.requestFocus();
                return;
            } else if (txtmob.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Mobile No", "Contact", 1);
                txtmob.requestFocus();
                return;
            } else if (cmbacctype.getSelectedItem().equals("Select")) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Select Account Type", "Branch", 1);
                cmbacctype.requestFocus();
                return;
            } else if (txtpan.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Adhar Card No.", "PAN", 1);
                txtpan.requestFocus();
                return;
            } else if (txtacc.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Account No", "Account", 1);
                txtacc.requestFocus();
                return;


            } else if (txtatmcard.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter ATM Card No.", "ATM Card", 1);
                txtatmcard.requestFocus();
                return;

            } else if (txtmob.getText().length() != 10) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Mobile No", "Contact", 1);
                txtmob.requestFocus();
                return;
            } else if (txtpan.getText().length() != 12) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Adhar Card No", "PAN No", 1);
                txtpan.requestFocus();
                return;
            } else if (txtatmcard.getText().length() != 16) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid ATM Card No", "ATM Card", 1);
                txtatmcard.requestFocus();
                return;
            } else if (txtacc.getText().length() != 16) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Account No", "Address", 1);
                txtacc.requestFocus();
                return;
            } else if (txtatmpin.getText().length() != 4) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid ATM Pin", "ATM Pin", 1);
                txtatmpin.requestFocus();
                return;
            } else if (txtaccesspin.getText().length() != 4) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Bank Access Pin", "Bank Pin", 1);
                txtaccesspin.requestFocus();
                return;
            }
            int s1 = 0;
            String s = txtmob.getText();
            for (int i = 0; i < s.length(); i++) {
                if (!Character.isDigit(s.charAt(i))) {
                    s1++;
                }
            }
            if (s1 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid Mobile No.", "Contact", 1);
                txtmob.requestFocus();
                return;
            }

            int s2 = 0;
            String s3 = txtacc.getText();
            for (int i = 0; i < s3.length(); i++) {
                if (!Character.isDigit(s3.charAt(i))) {
                    s2++;
                }
            }
            if (s2 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid Account No.", "Account", 1);
                txtacc.requestFocus();
                return;
            }
            int s4 = 0;
            String s5 = txtatmcard.getText();
            for (int i = 0; i < s5.length(); i++) {
                if (!Character.isDigit(s5.charAt(i))) {
                    s4++;
                }
            }
            if (s4 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid ATM Card No.", "aTM Card", 1);
                txtatmcard.requestFocus();
                return;
            }
            int s6 = 0;
            String s7 = txtatmpin.getText();
            for (int i = 0; i < s7.length(); i++) {
                if (!Character.isDigit(s7.charAt(i))) {
                    s6++;
                }
            }
            if (s6 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid ATM Pin.", "ATM Pin", 1);
                txtatmpin.requestFocus();
                return;
            }
            int s8 = 0;
            String s9 = txtaccesspin.getText();
            for (int i = 0; i < s9.length(); i++) {
                if (!Character.isDigit(s9.charAt(i))) {
                    s8++;
                }
            }
            if (s8 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid Bank Access Pin.", "Bank Pin", 1);
                txtaccesspin.requestFocus();
                return;
            }

            String name = txtname.getText();
            String patternvalidation = "[a-zA-Z \\s]+\\.?";
            pattern = Pattern.compile(patternvalidation);
            matcher = pattern.matcher(name);
            if (!matcher.matches()) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Name", "Name", 1);
                txtname.requestFocus();
                return;
            }

            String email = txtmail.getText();
            String patternvalidation1 = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
            pattern = Pattern.compile(patternvalidation1);
            matcher = pattern.matcher(email);
            if (!matcher.matches()) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Email-Id", "Email", 1);
                txtname.requestFocus();
                return;
            }

            st = db.DBC();
            int abc=st.executeUpdate("update tbluserlogin set email='" + txtmail.getText() + "', disabledate='0000-00-00', disablecount='0', disable='0' where email='"+oldmail+"'");
            InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\complete.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            JOptionPane.showMessageDialog(rootPane, "Customer Record Updated successfully", "Save", 1);
            int q = st.executeUpdate("update tbluserdetails set acctype='" + cmbacctype.getSelectedItem() + "', accno='" + txtacc.getText() + "', name='" + txtname.getText() + "', address='" + txtaddr.getText() + "', email='" + txtmail.getText() + "', regmob='" + txtmob.getText() + "', atmpin='" + txtatmpin.getText() + "', atmcard='" + txtatmcard.getText() + "', bankname='" + txtbname.getText() + "', bcode='" + txtifsc.getText() + "', pan='" + txtpan.getText() + "', accesspin='" + txtaccesspin.getText() + "' where accno='" + accno + "'");
            
            clearform();
            txtname.requestFocus();
            return;


        } catch (SQLException ex) {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        clearform();
}//GEN-LAST:event_btnresetActionPerformed

    private void txtatmpinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtatmpinKeyPressed
        if (evt.getKeyCode() == 10) {
            //btnsaveActionPerformed(null);
            txtaccesspin.requestFocus();
        }
}//GEN-LAST:event_txtatmpinKeyPressed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {

            int s = JOptionPane.showConfirmDialog(null, "Wolud you like to delete this record?", "Warning", JOptionPane.YES_NO_OPTION);
            if (s == 0) {
                st = db.DBC();
                int q = st.executeUpdate("delete from tbluserdetails where accno='" + txtacc.getText() + "'");
                int qq = st.executeUpdate("delete from tbluserlogin where email='" + txtmail.getText() + "'");
                if (q > 0) {
                    InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\complete.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                    JOptionPane.showMessageDialog(rootPane, "User record deleted successfully", "Delete", 1);
                    clearform();
                    return;
                } else {
                    InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                    JOptionPane.showMessageDialog(rootPane, "Error..! Record cannot be deleted", "Delete", 0);
                    return;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtbname.setText(lgn);
        txtifsc.setText(bcode);
        jLabel19.setVisible(false);
        jLabel32.setVisible(false);
        txtaccesspin.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        if (evt.getKeyCode() == 10) {
            txtaddr.requestFocus();
        }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmailKeyPressed
        if (evt.getKeyCode() == 10) {
            txtmob.requestFocus();
        }
    }//GEN-LAST:event_txtmailKeyPressed

    private void txtmobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobKeyPressed
        if (evt.getKeyCode() == 10) {
            cmbacctype.requestFocus();
        }
    }//GEN-LAST:event_txtmobKeyPressed

    private void cmbacctypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbacctypeKeyPressed
        if (evt.getKeyCode() == 10) {
            txtpan.requestFocus();
        }
    }//GEN-LAST:event_cmbacctypeKeyPressed

    private void txtpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpanKeyPressed
        if (evt.getKeyCode() == 10) {
            try {
                st = db.DBC();
                ResultSet rs = st.executeQuery("select * from tbluserdetails where pan='" + txtpan.getText() + "'");
                if (rs.next()) {
                    txtatmcard.setText(rs.getString("atmcard"));
                    txtatmpin.setText(rs.getString("atmpin"));
                    txtatmcard.setEditable(false);
                    txtatmpin.setEditable(false);
                    txtatmcard.setBackground(Color.white);
                    txtatmpin.setBackground(Color.white);
                }
                txtacc.requestFocus();
            } catch (SQLException ex) {
                Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtpanKeyPressed

    private void txtaccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccKeyPressed
        if (evt.getKeyCode() == 10) {
            txtatmcard.requestFocus();
        }
    }//GEN-LAST:event_txtaccKeyPressed

    private void txtatmcardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtatmcardKeyPressed
        if (evt.getKeyCode() == 10) {
            try {
                st = db.DBC();
                rs = st.executeQuery("select pan from tbluserdetails where atmcard='" + txtatmcard.getText() + "'");
                if (rs.next()) {
                    if (txtpan.getText().equals(rs.getString("pan"))) {
                        txtatmpin.requestFocus();

                    } else {
                        InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                        JOptionPane.showMessageDialog(rootPane, "ATM Card Already Exists");

                        return;
                    }
                }



            } catch (SQLException ex) {
                Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtatmcardKeyPressed

    private void txtaccesspinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccesspinKeyPressed
        if (evt.getKeyCode() == 10) {
            btnsaveActionPerformed(null);
        }
    }//GEN-LAST:event_txtaccesspinKeyPressed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed

        this.dispose();
}//GEN-LAST:event_btncloseActionPerformed

    private void txtaccesspinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccesspinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccesspinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UserDetails("", "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox cmbacctype;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtacc;
    private javax.swing.JPasswordField txtaccesspin;
    private javax.swing.JTextArea txtaddr;
    private javax.swing.JTextField txtatmcard;
    private javax.swing.JPasswordField txtatmpin;
    private javax.swing.JTextField txtbname;
    private javax.swing.JTextField txtifsc;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpan;
    // End of variables declaration//GEN-END:variables

    private void clearform() {
        txtacc.setText("");
        txtaddr.setText("");
        txtatmcard.setText("");
        txtatmpin.setText("");
        txtmail.setText("");
        txtmob.setText("");
        txtname.setText("");
        cmbacctype.setSelectedItem("Select");
        txtaccesspin.setText("");
        txtpan.setText("");
    }
}
