/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientMaster.java
 *
 * 
 */
package imfromatm;

import sun.audio.*;
import java.io.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author maaz gheewale
 */
public class BankMaster extends javax.swing.JFrame {

    Statement st, st1;
    ResultSet rs;
    String reg = "", branch = "", sem = "";
    DBConnection db = new DBConnection();
    String lgn = "";
    String tmpifsc = "";
    String tmpbcode = "";
    static Pattern pattern = null;
    static Matcher matcher = null;

    /** Creates new form ClientMaster */
    public BankMaster() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtbranch = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtcode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtifsc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtcont = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtrepass = new javax.swing.JPasswordField();
        btndelete = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        txtbranch.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtbranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtbranch.setName("txtbranch"); // NOI18N

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtname.setName("txtname"); // NOI18N

        txtcode.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcode.setName("txtcode"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel11.setText("Address           ");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel12.setText("IFSC Code       ");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel8.setText("Bank Name  ");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel9.setText("Branch Code      ");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel10.setText("Branch            ");
        jLabel10.setName("jLabel10"); // NOI18N

        txtifsc.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtifsc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtifsc.setName("txtifsc"); // NOI18N
        txtifsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtifscKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Bank Master");
        jLabel1.setName("jLabel1"); // NOI18N

        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnsave.setText("Save");
        btnsave.setName("btnsave"); // NOI18N
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsaveMouseEntered(evt);
            }
        });
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        btnsave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnsaveKeyPressed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btnsearch.setText("Search");
        btnsearch.setName("btnsearch"); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btnedit.setText("Edit");
        btnedit.setEnabled(false);
        btnedit.setName("btnedit"); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btnreset.setText("Reset");
        btnreset.setName("btnreset"); // NOI18N
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel13.setText("Contact No      ");
        jLabel13.setName("jLabel13"); // NOI18N

        txtcont.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtcont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcont.setName("txtcont"); // NOI18N
        txtcont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel14.setText("Password          ");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel15.setText("Re-Enter Password    ");
        jLabel15.setName("jLabel15"); // NOI18N

        txtpass.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpass.setName("txtpass"); // NOI18N

        txtrepass.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtrepass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtrepass.setName("txtrepass"); // NOI18N
        txtrepass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrepassKeyPressed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btndelete.setText("Delete");
        btndelete.setEnabled(false);
        btndelete.setName("btndelete"); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclose.setFont(new java.awt.Font("Times New Roman", 1, 18));
        btnclose.setText("Cancel");
        btnclose.setName("btnclose"); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtaddress.setRows(5);
        txtaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtaddress.setName("txtaddress"); // NOI18N
        jScrollPane1.setViewportView(txtaddress);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel8, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtifsc, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtbranch)
                        .addComponent(txtcode)
                        .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                        .addComponent(txtcont)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                        .addComponent(txtpass)
                        .addComponent(txtrepass)))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtifsc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtcont, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtrepass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsearch)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnsave)
                                .addComponent(btnreset)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnedit)
                            .addComponent(btnclose)))
                    .addComponent(btndelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
            // TODO add your handling code here:
            if (txtname.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Bank Name. ", "Bank Name", 1);
                txtname.requestFocus();
                return;
            } else if (txtcode.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Branch Code", "Bank Code", 1);
                txtcode.requestFocus();
                return;
            } else if (txtbranch.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Branch", "Branch", 1);
                txtbranch.requestFocus();
                return;
            } else if (txtaddress.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Bank Address", "Address", 1);
                txtaddress.requestFocus();
                return;
            } else if (txtifsc.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter IFSC Code", "IFSC Code", 1);
                txtifsc.requestFocus();
                return;
            } else if (txtcont.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Contact", "Contact", 1);
                txtcont.requestFocus();
                return;
            } else if (txtpass.getText().equals("")) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Password", "Password", 1);
                txtpass.requestFocus();
                return;
            } else if (txtrepass.getText().equals("")) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Re-enter Password", "Password", 1);
                txtrepass.requestFocus();
                return;
            } else if (txtifsc.getText().length() != 11) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Digit for IFSC Code", "IFSC Code", 1);
                txtifsc.requestFocus();
                return;
            } else if (txtcont.getText().length() != 11) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid 11 Digits LandLIne No", "Contact", 1);
                txtcont.requestFocus();
                return;
            } else if (txtpass.getText().equals(txtrepass.getText())) {

                int s1 = 0;
                String s = txtcont.getText();
                for (int i = 0; i < s.length(); i++) {
                    if (!Character.isDigit(s.charAt(i))) {
                        s1++;
                    }
                }
                if (s1 > 0) {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Invalid contact no.", "Contact", 1);
                    txtcont.requestFocus();
                    return;
                }
                String name = txtname.getText();
                String patternvalidation = "[a-zA-Z \\s]+\\.?";
                pattern = Pattern.compile(patternvalidation);
                matcher = pattern.matcher(name);
                if (!matcher.matches()) {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Bank Name", "Bank Name", 1);
                    txtname.requestFocus();
                    return;
                }
                String name1 = txtcode.getText();
                String patternvalidation1 = "[A-Z0-9]+\\.?";
                pattern = Pattern.compile(patternvalidation1);
                matcher = pattern.matcher(name1);
                if (!matcher.matches()) {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Branch Code", "Branch Code", 1);
                    txtcode.requestFocus();
                    return;
                }
                String name2 = txtifsc.getText();
                String patternvalidation2 = "[A-Z0-9]+\\.?";
                pattern = Pattern.compile(patternvalidation2);
                matcher = pattern.matcher(name2);
                if (!matcher.matches()) {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Please Enter Valid IFSC Code", "IFSC Code", 1);
                    txtifsc.requestFocus();
                    return;
                }



                st = db.DBC();
                st1 = db.DBC();
                rs = st.executeQuery("select * from tblbank where ifsccode='" + txtifsc.getText() + "'");
//                boolean f =rs.next();
//                System.out.print(f);
//               if (f==false) {
                if (rs.next()) {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Bank record already present with IFSC Code: " + txtifsc.getText(), "Save", 0);
                    txtifsc.requestFocus();
                    return;


                } else {
                    int q = st.executeUpdate("insert into tblbank values('" + txtname.getText() + "','" + txtcode.getText() + "','" + txtbranch.getText() + "','" + txtaddress.getText() + "','" + txtifsc.getText() + "','" + txtcont.getText() + "','" + txtpass.getText() + "')");
                    // int q1 =st.executeUpdate("insert into login values('"+txtname.getText() +"','"+txtpass.getText() +"','"+txtcode.getText()+"')");
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\complete.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Bank Record Added successfully", "Save", 1);
                    clearform();
                    txtname.requestFocus();
                    return;


                }
            } else {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Password Does Not Match!", "Password", 1);
                txtpass.setText("");
                txtrepass.setText("");
                txtpass.requestFocus();
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(BankMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        st = db.DBC();
        int i = 0;
        String r = JOptionPane.showInputDialog("Enter IFSC Code", "IFSC Code");
        if ((r.equals("IFSC Code") && r.equals(""))) {
            return;
        } else {
            try {
                rs = st.executeQuery("Select * from tblbank where ifsccode='" + r + "'");
                while (rs.next()) {
                    i++;
                    txtname.setText(rs.getString("bankname"));
                    txtcode.setText(rs.getString("bcode"));
                    txtbranch.setText(rs.getString("branch"));
                    txtaddress.setText(rs.getString("addr"));
                    txtifsc.setText(rs.getString("ifsccode"));
                    txtcont.setText(rs.getString("contact"));
                    txtpass.setEditable(false);
                    txtrepass.setEditable(false);
                    tmpifsc = txtifsc.getText();
                    tmpbcode = txtcode.getText();
                }
                if (i > 0) {
                    btnsave.setEnabled(false);
                    btnsearch.setEnabled(true);
                    btnedit.setEnabled(true);
                    btndelete.setEnabled(true);

                } else {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Invalid IFSC Code", "Search", 1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(BankMaster.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        clearform();
        txtpass.setEditable(true);
        txtrepass.setEditable(true);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        try {
            // TODO add your handling code here:
            if (txtname.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Bank Name. ", "Bank Name", 1);
                txtname.requestFocus();
                return;
            } else if (txtcode.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Bank Code", "Bank Code", 1);
                txtcode.requestFocus();
                return;
            } else if (txtbranch.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Branch", "Branch", 1);
                txtbranch.requestFocus();
                return;
            } else if (txtaddress.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Bank Address", "Address", 1);
                txtaddress.requestFocus();
                return;
            } else if (txtifsc.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter IFSC Code", "IFSC Code", 1);
                txtifsc.requestFocus();
                return;
            } else if (txtcont.getText().trim().length() == 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Contact Number", "Contact", 1);
                txtcont.requestFocus();
            } else if (txtifsc.getText().length() != 11) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid Digit for IFSC Code", "IFSC Code", 1);
                txtifsc.requestFocus();
                return;
            } else if (txtcont.getText().length() != 11) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter valid 11 Digits LandLIne No", "Contact", 1);
                txtcont.requestFocus();
                return;
            }
            int s1 = 0;
            String s = txtcont.getText();
            for (int i = 0; i < s.length(); i++) {
                if (!Character.isDigit(s.charAt(i))) {
                    s1++;
                }
            }
            if (s1 > 0) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Invalid contact no.", "Contact", 1);
            }

            String name = txtname.getText();
            String patternvalidation = "[a-zA-Z]+\\.?";
            pattern = Pattern.compile(patternvalidation);
            matcher = pattern.matcher(name);
            if (!matcher.matches()) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Bank Name", "Bank Name", 1);
                txtname.requestFocus();
                return;
            }
            String name1 = txtcode.getText();
            String patternvalidation1 = "[A-Z0-9]+\\.?";
            pattern = Pattern.compile(patternvalidation1);
            matcher = pattern.matcher(name1);
            if (!matcher.matches()) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Valid Branch Code", "Branch Code", 1);
                txtcode.requestFocus();
                return;
            }
            String name2 = txtifsc.getText();
            String patternvalidation2 = "[A-Z0-9]+\\.?";
            pattern = Pattern.compile(patternvalidation2);
            matcher = pattern.matcher(name2);
            if (!matcher.matches()) {
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JOptionPane.showMessageDialog(rootPane, "Please Enter Valid IFSC Code", "IFSC Code", 1);
                txtifsc.requestFocus();
                return;
            }
            txtifsc.setEnabled(false);


            st = db.DBC();
            st1 = db.DBC();
            rs = st.executeQuery("select * from tblbank where ifsccode='" + txtifsc.getText() + "'");
//                boolean f =rs.next();
//                System.out.print(f);
//               if (f==false) {
            if (rs.next()) {
                int q = st.executeUpdate("update tblbank set bankname='" + txtname.getText() + "', bcode='" + txtcode.getText() + "', branch='" + txtbranch.getText() + "', addr='" + txtaddress.getText() + "', ifsccode='" + txtifsc.getText() + "', contact='" + txtcont.getText() + "' where ifsccode='" + tmpifsc + "'");
                InputStream in;
                try {
                    in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\complete.wav"));
                    AudioStream audios = new AudioStream(in);
                    AudioPlayer.player.start(audios);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                // int q1=st.executeUpdate("update login set username='"+txtname.getText()+"', bcode='"+  txtcode.getText() +"' where bcode='"+ tmpbcode +"'");
                JOptionPane.showMessageDialog(rootPane, "Bank Record Updated successfully", "Save", 1);
                clearform();
                return;

            }
        } catch (SQLException ex) {
            Logger.getLogger(BankMaster.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btneditActionPerformed

    private void txtrepassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrepassKeyPressed
        if (evt.getKeyCode() == 10) {
            btnsaveActionPerformed(null);
        }
    }//GEN-LAST:event_txtrepassKeyPressed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {


            int s = JOptionPane.showConfirmDialog(null, "Wolud you like to delete this record?", "Warning", JOptionPane.YES_NO_OPTION);
            if (s == 0) {
                st = db.DBC();
                int q = st.executeUpdate("delete from tblbank where ifsccode='" + txtifsc.getText() + "'");
                if (q > 0) {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\complete.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Bank record deleted successfully", "Delete", 1);
                    clearform();
                    return;
                } else {
                    InputStream in;
                    try {
                        in = new FileInputStream(new File("C:\\xampp\\htdocs\\MODULE1\\src\\imfromatm\\error.wav"));
                        AudioStream audios = new AudioStream(in);
                        AudioPlayer.player.start(audios);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(rootPane, "Error..! Record cannot be deleted", "Delete", 0);
                    return;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(BankMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtifscKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtifscKeyPressed
    }//GEN-LAST:event_txtifscKeyPressed

    private void btnsaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsaveKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveKeyPressed

    private void txtcontKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontKeyPressed
    }//GEN-LAST:event_txtcontKeyPressed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed

        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveMouseClicked

    private void btnsaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BankMaster().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtbranch;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtcont;
    private javax.swing.JTextField txtifsc;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JPasswordField txtrepass;
    // End of variables declaration//GEN-END:variables

    private void clearform() {
        txtname.setText("");
        txtbranch.setText("");
        txtcode.setText("");
        txtcont.setText("");
        txtifsc.setText("");
        txtaddress.setText("");
        txtpass.setText("");
        txtrepass.setText("");
    }
}
